<?php

namespace Australopithecus\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductPicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPicturesRepository extends EntityRepository
{
}
